In [1]:
import torch
import torch.nn as nn

In [4]:
#  定义全连接层
linear = nn.Linear(in_features=5, out_features=2)


In [5]:
# 1.常数初始化，原地修改
# 默认都是打开梯度计算的
nn.init.zeros_(linear.weight)


'\nParameter containing:\ntensor([[0., 0., 0.],\n        [0., 0., 0.],\n        [0., 0., 0.],\n        [0., 0., 0.],\n        [0., 0., 0.]], requires_grad=True)\n'

In [7]:
nn.init.constant_(linear.weight,val=10)
print(linear.weight)

'''
Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)
'''

Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


'\nParameter containing:\ntensor([[10., 10., 10., 10., 10.],\n        [10., 10., 10., 10., 10.]], requires_grad=True)\n'

In [8]:
# 2.秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)
'''
Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)
'''

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [9]:
# 3.正态分布初始化
nn.init.normal_(linear.weight,mean=0,std=0.1)
'''
Parameter containing:
tensor([[-0.1741, -0.0342, -0.0686,  0.0821, -0.0772],
        [ 0.0188, -0.1215, -0.0445, -0.0139, -0.0518]], requires_grad=True)
'''

Parameter containing:
tensor([[-0.1741, -0.0342, -0.0686,  0.0821, -0.0772],
        [ 0.0188, -0.1215, -0.0445, -0.0139, -0.0518]], requires_grad=True)

In [10]:
# 4.均匀分布初始化
nn.init.uniform_(linear.weight,a=-1,b=1)
print(linear.weight)
'''
Parameter containing:
tensor([[ 0.8869, -0.9012, -0.6878,  0.6742,  0.2117],
        [-0.9875,  0.7019, -0.3415,  0.7891,  0.8187]], requires_grad=True)
'''


Parameter containing:
tensor([[ 0.8869, -0.9012, -0.6878,  0.6742,  0.2117],
        [-0.9875,  0.7019, -0.3415,  0.7891,  0.8187]], requires_grad=True)


In [11]:
# 5.Xavier 正态分布初始化
nn.init.xavier_normal_(linear.weight)
print(linear.weight)
'''
Parameter containing:
tensor([[ 0.2658,  0.6250, -0.3332, -0.6415,  0.1208],
        [ 0.0242,  0.3682, -0.1481,  0.6928, -0.6845]], requires_grad=True)
'''

Parameter containing:
tensor([[ 0.2658,  0.6250, -0.3332, -0.6415,  0.1208],
        [ 0.0242,  0.3682, -0.1481,  0.6928, -0.6845]], requires_grad=True)


In [13]:
# 6.Xavier 均匀分布初始化
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)
'''
Parameter containing:
tensor([[-0.2721,  0.4218,  0.2440,  0.8673,  0.1164],
        [ 0.8444, -0.3394, -0.1350, -0.7220, -0.4670]], requires_grad=True)
'''

Parameter containing:
tensor([[-0.0300, -0.0381, -0.8523,  0.2459,  0.0721],
        [-0.5710,  0.2439,  0.6630, -0.7453, -0.5337]], requires_grad=True)


'\nParameter containing:\ntensor([[-0.2721,  0.4218,  0.2440,  0.8673,  0.1164],\n        [ 0.8444, -0.3394, -0.1350, -0.7220, -0.4670]], requires_grad=True)\n'

In [14]:
# He初始化根据输入的神经元数量调整权重的初始范围。主要适用于ReLU及其变体（如Leaky ReLU）激活函数。

# Kaiming正态分布初始化
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

# Kaiming均匀分布初始化
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)
'''
Parameter containing:
tensor([[-0.9470,  0.0925,  1.0651,  0.7369, -0.2958],
        [-0.5351,  0.4352,  1.4885, -0.1159,  0.6237]], requires_grad=True)
Parameter containing:
tensor([[-0.7411,  0.9808,  0.3209,  0.2212, -0.1225],
        [-0.6376, -0.9666,  0.7588,  0.6826, -0.2438]], requires_grad=True)zhel
'''

Parameter containing:
tensor([[-0.9470,  0.0925,  1.0651,  0.7369, -0.2958],
        [-0.5351,  0.4352,  1.4885, -0.1159,  0.6237]], requires_grad=True)
Parameter containing:
tensor([[-0.7411,  0.9808,  0.3209,  0.2212, -0.1225],
        [-0.6376, -0.9666,  0.7588,  0.6826, -0.2438]], requires_grad=True)
