In [1]:
import torch
import torch.nn as nn


In [6]:
# 1.目标值为顺序编码的标签
input = torch.randn(6, 8)
print(input)
# pred = torch.softmax(input, dim=1)
# print(pred)

tensor([[-0.7794, -0.5312, -0.6833, -0.4827,  0.3359, -2.5459,  0.3009,  0.1526],
        [ 0.2290,  0.8550,  0.0315,  0.2590, -0.1573,  1.9260,  0.5805,  1.1594],
        [ 1.3229,  1.1262, -0.3146, -0.6146, -0.3115,  0.5615, -0.3843,  1.1218],
        [-0.6504, -0.5622, -0.7583,  1.2294,  2.6821, -0.5710, -1.6143, -0.7316],
        [ 0.2515, -0.4091,  0.7940,  1.7276, -0.9199,  0.8352,  0.6610,  0.3940],
        [-0.5150,  0.7263,  0.4917, -0.8217,  1.4942, -1.2376,  1.0574, -1.1666]])
tensor([[0.0744, 0.0954, 0.0819, 0.1001, 0.2271, 0.0127, 0.2193, 0.1890],
        [0.0675, 0.1262, 0.0554, 0.0696, 0.0459, 0.3684, 0.0959, 0.1711],
        [0.2617, 0.2150, 0.0509, 0.0377, 0.0511, 0.1222, 0.0475, 0.2140],
        [0.0250, 0.0273, 0.0225, 0.1641, 0.7013, 0.0271, 0.0096, 0.0231],
        [0.0808, 0.0417, 0.1390, 0.3536, 0.0250, 0.1449, 0.1217, 0.0932],
        [0.0471, 0.1631, 0.1290, 0.0347, 0.3515, 0.0229, 0.2271, 0.0246]])


In [10]:
# 目标值，6个数据的类别标签（0 ～7）
target = torch.tensor([1, 0, 7, 5, 2, 3])  # 6个标签，对应6个样本
print(target)

tensor([1, 0, 7, 5, 2, 3])


注意：调用torch.nn.CrossEntropyLoss相当于调用了torch.nn.LogSoftmax之后再调用torch.nn.NLLLoss。即使用CrossEntropyLoss时上一层的输出不需要Softmax激活函数，因为该损失函数内会自动处理

CrossEntropyLoss = LogSoftmax + NLLLoss

内部流程:
input (logits)
  ↓
LogSoftmax  ← 自动执行
  ↓
NLLLoss (负对数似然损失)
  ↓
loss value



In [12]:
# 定义损失函数
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.5882)


In [13]:
# 2.目标值为一组概率（独热编码）
input = torch.randn(6, 8)
print( input)

tensor([[-0.0295,  1.7190, -0.6976,  0.5637,  1.0324, -0.1565,  0.0384,  0.9307],
        [ 0.1546,  1.2834,  0.3259, -0.3570,  0.3939, -2.6589, -1.5708, -0.5817],
        [-0.1880,  1.5211,  2.2692, -0.1478,  0.9910, -0.3168,  0.1773,  0.0409],
        [-0.1744,  2.4967, -0.0049, -1.5835, -0.1075,  0.9283,  0.0455,  0.7647],
        [ 2.6766,  1.1239, -0.7716,  0.8022, -0.6867,  0.8704,  1.2580, -2.0432],
        [-0.1132,  0.2082,  0.3648, -0.2711,  0.9001,  0.7012, -0.3526, -0.2929]])


In [ ]:
target = torch.randn(6,8).softmax(dim=1) # 按照行进行处理
print(target)

In [14]:
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.4863)
