In [6]:
import torch
import numpy as np

##  1.基本张量创建

（1）按内容创建张量

In [4]:
# 传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)
print(tensor1.dtype)
print(tensor1.size())

tensor(10)
torch.int64
torch.Size([])


In [5]:
# 传入一维数组
tensor2 = torch.tensor([1, 2, 3])
print(tensor2)
print(tensor2.dtype)
print(tensor2.size())

tensor([1, 2, 3])
torch.int64
torch.Size([3])


In [7]:
# 传入二维数组
tensor3 = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
print(tensor3)
print(tensor3.dtype)
print(tensor3.size())
'''
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])
'''

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])


## （2） 创建指定形状的张量

In [8]:

# 就是一个 3维张量
# 第0维: 3  → 有3个"块"
# 第1维: 2  → 每个块有2行
# 第2维: 4  → 每行有4列
# 总元素数: 3 × 2 × 4 = 24 个元素
# torch.Tensor(3, 2, 4) 这种写法会创建一个未初始化的张量，里面的值是随机的内存数据（不推荐）。

'''
Tensor shape: (3, 2, 4)

Block 0:          Block 1:          Block 2:
[[_, _, _, _],    [[_, _, _, _],    [[_, _, _, _],
 [_, _, _, _]]     [_, _, _, _]]     [_, _, _, _]]

'''

tensor1 = torch.Tensor(3, 2, 4)
print(tensor1)
print(tensor1.dtype)
print(tensor1.size())

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.float32
torch.Size([3, 2, 4])


In [9]:
tensor2 = torch.Tensor([[1, 2, 3, 4], [4, 5, 6, 7]])
print(tensor2)
print(tensor2.dtype)
print(tensor2.size())

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])
torch.float32
torch.Size([2, 4])


# ✅ 方法1: 创建全零张量
tensor1 = torch.zeros(3, 2, 4)

# ✅ 方法2: 创建全一张量
tensor1 = torch.ones(3, 2, 4)

# ✅ 方法3: 创建随机张量
tensor1 = torch.rand(3, 2, 4)

# ✅ 方法4: 从列表创建
tensor1 = torch.tensor([[[1,2,3,4], [5,6,7,8]],
                        [[9,10,11,12], [13,14,15,16]],
                        [[17,18,19,20], [21,22,23,24]]])


In [ ]:
import torch

tensor1 = torch.rand(3, 2, 4)

# 方法1: 使用 .shape 属性
print(tensor1.shape)  # 输出: torch.Size([3, 2, 4])

# 方法2: 使用 .size() 方法
print(tensor1.size())  # 输出: torch.Size([3, 2, 4])

# 方法3: 获取特定维度的大小
print(tensor1.size(0))  # 输出: 3 (第0维)
print(tensor1.size(1))  # 输出: 2 (第1维)
print(tensor1.size(2))  # 输出: 4 (第2维)

# 方法4: 查看维度数
print(tensor1.ndim)  # 输出: 3 (3维张量)

# 方法5: 查看总元素数
print(tensor1.numel())  # 输出: 24 (3×2×4)






3维张量常用于:
- NLP: (batch_size, sequence_length, embedding_dim)
  例如: (32, 100, 768) - 32个句子，每句100词，每个词768维嵌入

- 时间序列: (batch_size, time_steps, features)
  例如: (64, 50, 10) - 64个样本，每个50个时间步，每步10个特征

- 彩色图像批次: (batch_size, channels, height, width)
  例如: (16, 3, 224, 224) - 16张图片，RGB 3通道，224×224像素


## （3） 创建指定类型的张量

In [12]:
# int （int32）类型
tensor1 = torch.IntTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int32)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int32
torch.int32


In [13]:
# int （int64）类型
tensor1 = torch.LongTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int64
torch.int64


In [14]:
# int （int16）类型
tensor1 = torch.ShortTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int16)
print(tensor1.dtype)
print(tensor2.dtype)

torch.int16
torch.int16


In [15]:
tensor1 = torch.ByteTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.int8)
print(tensor1.dtype)
print(tensor2.dtype)

torch.uint8
torch.int8


In [16]:
# float 类型
tensor1 = torch.FloatTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float32)
print(tensor1.dtype)
print(tensor2.dtype)

torch.float32
torch.float32


In [18]:
# double 类型
tensor1 = torch.DoubleTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float64)
print(tensor1.dtype)
print(tensor2.dtype)

torch.float64
torch.float64


In [19]:
# half 类型
tensor1 = torch.HalfTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.float16)
print(tensor1.dtype)
print(tensor2.dtype)

torch.float16
torch.float16


In [20]:
# bool 类型
tensor1 = torch.BoolTensor(2, 3)
tensor2 = torch.tensor([1, 2, 3], dtype=torch.bool)
print(tensor1.dtype)
print(tensor2.dtype)
print(tensor1)
print(tensor2)

torch.bool
torch.bool
tensor([[False, False, False],
        [False, False, False]])
tensor([True, True, True])


## 指定区间的张量创建

In [21]:
# 左闭右开
tensor1 = torch.arange(10, 30, 2)
print(tensor1)
# tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])


In [22]:
tensor2 = torch.arange(6)
print(tensor2)  # tensor([0, 1, 2, 3, 4, 5])

tensor([0, 1, 2, 3, 4, 5])


In [23]:
# 在区间按元素数量创建张量
tensor2 = torch.linspace(10, 30, 6)
print(tensor2)  # tensor([10., 14., 18., 22., 26., 30.])

tensor([10., 14., 18., 22., 26., 30.])


In [24]:
# torch.logspace(start, end, steps, base) 在区间[start,end]之间生成steps个数，并以base为底，区间内的数为指数创建张量
tensor1 = torch.logspace(1, 3, 3, base=2)
print(tensor1)

tensor([2., 4., 8.])


## 按数值填充张量

In [ ]:
# torch.zeros(size) 创建指定形状的全0张量
tensor1 = torch.zeros(2, 3)
print(tensor1)

# torch.ones_like(input) 创建与给定张量形状相同的全1张量
tensor2 = torch.ones_like(tensor1)
print(tensor2)

# torch.full(size,fill_value) 创建指定形状的按指定值填充的张量
tensor1 = torch.full((2, 3), 6)
print(tensor1)

# torch.empty_like(input) 创建与给定张量形状相同的未初始化的张量
tensor2 = torch.empty_like(tensor3)
print(tensor2)

# torch.eye(n) 创建n*n的单位矩阵
tensor1 = torch.eye(3)
print(tensor1)

# torch.eye(n, m) 按指定的行和列创建
tensor2 = torch.eye(3, 4)
print(tensor2)

## 随机张量创建

In [26]:
# torch.rand(size) 创建在[0,1)上均匀分布的，指定形状的张量
tensor1 = torch.rand(2, 3)
print(tensor1)

tensor([[0.4763, 0.6444, 0.7517],
        [0.4179, 0.2917, 0.8731]])


In [ ]:
# torch.rand_like(input) 创建在[0,1)上均匀分布的，与给定张量形状相同的张量
tensor2 = torch.randint_like(tensor1, 1, 10)
print(tensor2)

In [ ]:
# torch.normal(mean,std,size) 创建自定义正态分布的，指定形状的张量。mean为均值，std为标准差
tensor2 = torch.normal(5, 1, tensor1.shape)
print(tensor2)

In [25]:
# torch.randn(size) 创建标准正态分布的，指定形状的张量
tensor1 = torch.randn(4, 2)
print(tensor1)

tensor([[-0.5059, -2.1483],
        [-0.2951, -1.3895],
        [-0.9424,  1.0616],
        [ 0.6885,  0.5811]])


In [ ]:
# torch.randperm(n) 生成从0到n-1的随机排列
tensor1 = torch.randperm(10)
print(tensor1)

In [27]:
# 查看随机数种子
print(torch.random.initial_seed())
# 设置随机数种子
torch.manual_seed(42)
print(torch.random.initial_seed())

8372653696938287341
42
