In [1]:
import torch
import numpy as np

## 张量元素类型转换

In [4]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1, tensor1.dtype)

# 转成复数
tensor1 = tensor1.type(torch.complex64)
print(tensor1, tensor1.dtype)

# tensor([1, 2, 3]) torch.int64
# tensor([1.+0.j, 2.+0.j, 3.+0.j]) torch.complex64


tensor([1, 2, 3]) torch.int64
tensor([1.+0.j, 2.+0.j, 3.+0.j]) torch.complex64


In [2]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1, tensor1.dtype)

# 使用type方法修改张量的类型
tensor1 = tensor1.type(torch.float32)
print(tensor1, tensor1.dtype)
# tensor([1, 2, 3]) torch.int64
# tensor([1., 2., 3.]) torch.float32

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32


In [3]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1, tensor1.dtype)

# 使用double方法修改张量的类型
tensor1 = tensor1.double()
print(tensor1)
# 使用long方法修改张量的类型
tensor1 = tensor1.long()
print(tensor1, tensor1.dtype)

'''
tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3]) torch.int64
'''



tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1, 2, 3]) torch.int64


## Tensor与ndarray转换

1）Tensor.numpy()将Tensor转换为ndarray，共享内存。使用copy()避免共享内存

In [5]:
# 1.tensor => ndarray
tensor1 = torch.tensor([1, 2, 3])
ndarray1 = tensor1.numpy()
print(tensor1, ndarray1)

tensor([1, 2, 3]) [1 2 3]


In [8]:
# 精度一致
np.set_printoptions(precision=3)
torch.set_printoptions(precision=3)
tensor1 = torch.rand(3, 2)
ndarray1 = tensor1.numpy()
print(tensor1, ndarray1)

tensor([[0.221, 0.554],
        [0.963, 0.461],
        [0.371, 0.807]]) [[0.221 0.554]
 [0.963 0.461]
 [0.371 0.807]]


In [9]:
# 使用copy()方法避免共享内存
numpy_array = tensor1.numpy().copy()
# 切片操作 tensor1[:, 0] = -1 取的是**所有行的第0列（第一列）**的数据
tensor1[:, 0] = -1
print(tensor1)
print(numpy_array)

tensor([[-1.000,  0.554],
        [-1.000,  0.461],
        [-1.000,  0.807]])
[[0.221 0.554]
 [0.963 0.461]
 [0.371 0.807]]


切片语法            含义                  示例结果
tensor[:, 0]     所有行的第0列          [1, 5, 9]
tensor[0, :]     第0行的所有列          [1, 2, 3, 4]
tensor[:, :]     所有元素（整个张量）     完整张量
tensor[1:3, :]   第1到第2行（不包括3）    中间两行
tensor[:, ::2]   所有行，每隔一列取一个    偶数列
tensor[::-1, :]  所有行逆序             行翻转

In [11]:
# 常见的切片操作

tensor1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 示例1: 取所有行的第0列
print(tensor1[:, 0])      # 输出: tensor([1, 5, 9])

# 示例2: 取第0行的所有列
print(tensor1[0, :])      # 输出: tensor([1, 2, 3, 4])

# 示例3: 取第0行第0列的单个元素
print(tensor1[0, 0])      # 输出: tensor(1)

# 示例4: 取前2行的所有列
print(tensor1[:2, :])     # 输出: tensor([[1, 2, 3, 4],
                          #                [5, 6, 7, 8]])

# 示例5: 取所有行的第1到第3列（不包括第3列）
print(tensor1[:, 1:3])    # 输出: tensor([[ 2,  3],
                          #                [ 6,  7],
                          #                [10, 11]])

# 示例6: 取所有行的最后一列
print(tensor1[:, -1])     # 输出: tensor([4, 8, 12])


tensor([1, 5, 9])
tensor([1, 2, 3, 4])
tensor(1)
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])
tensor([ 4,  8, 12])


In [10]:
import torch

# 创建一个 3×4 的张量
tensor1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("原始张量:")
print(tensor1)
# 输出:
# tensor([[ 1,  2,  3,  4],
#         [ 5,  6,  7,  8],
#         [ 9, 10, 11, 12]])

# 执行切片赋值
tensor1[:, 0] = -1

print("\n赋值后的张量:")
print(tensor1)
# 输出:
# tensor([[-1,  2,  3,  4],
#         [-1,  6,  7,  8],
#         [-1, 10, 11, 12]])


原始张量:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

赋值后的张量:
tensor([[-1,  2,  3,  4],
        [-1,  6,  7,  8],
        [-1, 10, 11, 12]])


In [12]:
# 高维张量
tensor3d = torch.rand(3, 2, 4)
print(tensor3d.shape)
print(tensor3d)

# 取所有"块"的第0行、所有列
tensor3d[:, 0, :]  # 形状: (3, 4)

# 取第0个"块"的所有行、第0列
tensor3d[0, :, 0]  # 形状: (2,)

# 取所有"块"、所有行、第0列
tensor3d[:, :, 0]  # 形状: (3, 2)


torch.Size([3, 2, 4])
tensor([[[0.287, 0.796, 0.644, 0.144],
         [0.473, 0.563, 0.619, 0.324]],

        [[0.828, 0.784, 0.284, 0.589],
         [0.441, 0.445, 0.116, 0.917]],

        [[0.095, 0.768, 0.757, 0.615],
         [0.026, 0.189, 0.196, 0.173]]])


tensor([[0.287, 0.473],
        [0.828, 0.441],
        [0.095, 0.026]])

2）torch.from_numpy(ndarray)将ndarray转换为Tensor，共享内存。使用copy()避免共享内存

In [15]:
# ndarray => tensor
ndarray1 = np.random.randn(3,2)
tensor1 = torch.from_numpy(ndarray1)
print(ndarray1, tensor1)
# 存在共享内存的问题
# ndarray1[:,0] = -1
# print(ndarray1, tensor1)

[[ 0.453  0.831]
 [-0.077  0.812]
 [ 0.822 -0.416]] tensor([[ 0.453,  0.831],
        [-0.077,  0.812],
        [ 0.822, -0.416]], dtype=torch.float64)


In [20]:
# 使用copy()方法避免共享内存
tensor2 = torch.from_numpy(ndarray1.copy())
ndarray1[:,0] = -7
print(ndarray1)
print(tensor1)
print(tensor2)

[[-7.     0.831]
 [-7.     0.812]
 [-7.    -0.416]]
tensor([[-7.000,  0.831],
        [-7.000,  0.812],
        [-7.000, -0.416]], dtype=torch.float64)
tensor([[-7.000,  0.831],
        [-7.000,  0.812],
        [-7.000, -0.416]], dtype=torch.float64)


3）torch.tensor(ndarray)将ndarray转换为Tensor，不共享内存

In [21]:
# 使用torch.tensor()将ndarray转换为Tensor
numpy_array = np.random.randn(3)
tensor1 = torch.tensor(numpy_array)
print(numpy_array)
print(tensor1)
print()
numpy_array[0] = 100
print(numpy_array)
print(tensor1)


[-0.522  0.09  -1.628]
tensor([-0.522,  0.090, -1.628], dtype=torch.float64)

[100.      0.09   -1.628]
tensor([-0.522,  0.090, -1.628], dtype=torch.float64)


## Tensor与标量转换
若张量中只有1个元素，Tensor.item()可提取张量中元素为标量。

In [22]:
tensor1 = torch.tensor(1)
print(tensor1)
print(tensor1.item())
'''
tensor(1)
1
'''

tensor(1)
1
