In [15]:
import torch
import numpy as np

# 张量数值计算

基本运算

1）四则运算
+、-、*、/加减乘除

add()、sub()、mul()、div()加减乘除，不改变原数据

add_()、sub_()、mul_()、div_()加减乘除、修改原数据


In [2]:
# 1.四则运算
tensor1 = torch.randint(0, 10, (2, 3))
print(tensor1)

tensor([[0, 7, 2],
        [2, 4, 7]])


In [3]:
print(tensor1 + 10)

tensor([[10, 17, 12],
        [12, 14, 17]])


In [6]:
print(tensor1.add_(10)) # 修改原始数据
print(tensor1)


tensor([[10, 17, 12],
        [12, 14, 17]])
tensor([[10, 17, 12],
        [12, 14, 17]])


In [7]:
print(tensor1.sub_(10)) # 修改原始数据
print(tensor1)

tensor([[0, 7, 2],
        [2, 4, 7]])
tensor([[0, 7, 2],
        [2, 4, 7]])


In [9]:
# 幂函数
print(tensor1.pow(2))
print(tensor1)

tensor([[ 0, 49,  4],
        [ 4, 16, 49]])
tensor([[0, 7, 2],
        [2, 4, 7]])


In [10]:
print(tensor1.sqrt())
print(tensor1)

tensor([[0.0000, 2.6458, 1.4142],
        [1.4142, 2.0000, 2.6458]])
tensor([[0, 7, 2],
        [2, 4, 7]])


In [ ]:
tensor1 = tensor1.float()
print(tensor1.sqrt_())
print(tensor1)

In [16]:
tensor1 = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])  # 使用浮点数，避免exp_()类型错误
print(tensor1)
print(2.7182818284 ** tensor1)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02, 4.0343e+02,
        1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04])


In [17]:
# exp()、exp_()以e为底数求幂
print(tensor1.exp())
print(tensor1)

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02, 4.0343e+02,
        1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [18]:
print(tensor1.exp_())

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02, 4.0343e+02,
        1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04])


log()、log_()以e为底求对数

In [19]:

tensor1 = torch.tensor([1.0, 2.0, 3.0])
print(tensor1.log())
print(tensor1)
print()

print(tensor1.log_())
print(tensor1)


tensor([0.0000, 0.6931, 1.0986])
tensor([1., 2., 3.])

tensor([0.0000, 0.6931, 1.0986])
tensor([0.0000, 0.6931, 1.0986])


## 哈达玛积（元素级乘法）

两个矩阵对应位置元素相乘称为哈达玛积（Hadamard product）。
使用*、mul()实现两个形状相同的张量之间对位相乘

In [20]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[1, 2], [3, 4]])
print(tensor1 * tensor2)
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [21]:
print(tensor1.mul(tensor2))

tensor([[ 1,  4],
        [ 9, 16]])


## 矩阵乘法运算
mm()严格用于二维矩阵相乘。
@、matmul()支持多维张量，按最后两个维度做矩阵乘法，其他维度相同，或者至少一个张量对应维度为1，广播后进行运算。


In [22]:

# 2维矩阵的矩阵乘法
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(tensor1)
print(tensor2)
print(tensor1.mm(tensor2))
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))
print()


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])



In [23]:
# 3维张量的矩阵乘法
tensor1 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[6, 5, 4], [3, 2, 1]]])
tensor2 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[6, 5], [4, 3], [2, 1]]])
print(tensor1)
print(tensor2)
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))


tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[6, 5, 4],
         [3, 2, 1]]])
tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[6, 5],
         [4, 3],
         [2, 1]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])
tensor([[[22, 28],
         [49, 64]],

        [[64, 49],
         [28, 22]]])


In [32]:
# 验证内存的共享和节省内存
X = torch.randint(1, 9, (3, 2, 4))
Y = torch.randint(1, 9, (3, 4, 1))

print(X)
print(id(X)) # 4429284208
# X = X @ Y
X  @=  Y # 这里会重新开辟空间
# 节省空间:如果后续X不再重复使用，可以使用X[:] = X @ Y来减少内存开销。
X[:] = X @ Y
print(id(X), end="\n\n")


tensor([[[3, 4, 6, 7],
         [8, 7, 6, 4]],

        [[1, 3, 2, 8],
         [3, 6, 8, 4]],

        [[2, 4, 2, 2],
         [4, 8, 1, 4]]])
4429284208


In [33]:
# X = X + 10
X += 10 # 改变原数据
print(id(X)) # 4429284208

4429284208
