# 张量运算函数

常见运算函数：
sum()求和
mean()求均值
max()/min()求最大/最小值及其索引
argmax()/argmin()求最大值/最小值的索引
std()求标准差
unique()去重
sort()排序

In [1]:
import torch

In [7]:
tensor1 = torch.randint(1,10,(3,2,4)).float()
print(tensor1)

tensor([[[8., 3., 7., 4.],
         [8., 7., 2., 3.]],

        [[3., 1., 1., 9.],
         [5., 8., 9., 9.]],

        [[4., 4., 2., 2.],
         [1., 3., 9., 3.]]])


In [8]:
# sum 求和 这里是所有元素
print(tensor1.sum())

tensor(115.)


In [9]:
# 按照维度求和，dim目前是三个维度
print(tensor1.sum(dim=0))

tensor([[15.,  8., 10., 15.],
        [14., 18., 20., 15.]])


In [10]:
# mean求均值
print(tensor1.mean())

tensor(4.7917)


In [11]:
# max() 求最大值
print("求最大值")
print(tensor1.max())
print("按第2个维度求最大值与索引")
print(tensor1.max(dim=2))
print()

求最大值
tensor(9.)
按第2个维度求最大值与索引
torch.return_types.max(
values=tensor([[8., 8.],
        [9., 9.],
        [4., 9.]]),
indices=tensor([[0, 0],
        [3, 2],
        [0, 2]]))



In [12]:
# std() 求标准差
print("求标准差")
print(tensor1.std())
print()

求标准差
tensor(2.9189)



In [ ]:
# argmin() 求最小值索引
print("求最小值索引")
print(tensor1.argmin())
print()

In [13]:
# max() 求最大值
print("求最大值")
print(tensor1.max())
print("按第2个维度求最大值与索引")
print(tensor1.max(dim=2))
print()


求最大值
tensor(9.)
按第2个维度求最大值与索引
torch.return_types.max(
values=tensor([[8., 8.],
        [9., 9.],
        [4., 9.]]),
indices=tensor([[0, 0],
        [3, 2],
        [0, 2]]))



In [14]:
# unique() 去重
print("去重")
print(tensor1.unique())
print()
'''
去重
tensor([1., 2., 3., 4., 5., 7., 8., 9.])
'''

去重
tensor([1., 2., 3., 4., 5., 7., 8., 9.])



In [15]:

# sort() 排序
print("排序")
print(tensor1.sort())


排序
torch.return_types.sort(
values=tensor([[[3., 4., 7., 8.],
         [2., 3., 7., 8.]],

        [[1., 1., 3., 9.],
         [5., 8., 9., 9.]],

        [[2., 2., 4., 4.],
         [1., 3., 3., 9.]]]),
indices=tensor([[[1, 3, 2, 0],
         [2, 3, 1, 0]],

        [[1, 2, 0, 3],
         [0, 1, 2, 3]],

        [[2, 3, 0, 1],
         [0, 1, 3, 2]]]))
