In [ ]:
import torch

In [ ]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)

In [ ]:
# 1.简单索引操作
print(tensor1[2, 1, 3])

In [ ]:
# 切片操作
print(tensor1[:, 3])

In [ ]:
# 范围索引
print(tensor1[1:])

In [ ]:
print(tensor1[-1])

In [ ]:
print(tensor1[-1:, 1:4, 0:3])

In [ ]:
# 1:4:2 最后一个2是步长（张量中的步长必须是正的）
print(tensor1[-1:, 1:4:2, 0:3])

In [ ]:
# 列表索引，注意对应关系
# 0 1
# 1 2
print(tensor1[[0, 1], [1, 2]])


In [ ]:
# 一对多的关系
print(tensor1[[[0], [1]], [1, 2]])


In [10]:
# 布尔索引
print(tensor1[tensor1 > 5])

tensor([9, 9, 8, 6, 7, 7, 7, 6, 9, 9, 9, 7, 6, 7, 9, 9, 6, 6, 6, 8, 7, 9, 7, 8,
        6, 6, 8, 9, 6])


In [12]:
# 选取符合条件的行，首元素大于 5
print(tensor1[:, :, 0] > 5)

tensor([[False,  True,  True,  True,  True],
        [False,  True,  True, False, False],
        [ True, False,  True, False, False]])


In [13]:
mask = tensor1[:, :, 0] > 5
print(tensor1[mask])

tensor([[9, 8, 3, 6],
        [7, 7, 7, 6],
        [9, 3, 9, 9],
        [7, 3, 6, 7],
        [9, 3, 1, 5],
        [6, 6, 6, 8],
        [7, 3, 2, 9],
        [6, 2, 8, 2]])


In [16]:
# 选取符合条件的列，第二个元素大于 5
print(tensor1[:, 1, :] > 5)

tensor([[ True,  True, False,  True],
        [ True, False, False, False],
        [False,  True,  True,  True]])


In [18]:
mask = tensor1[:, 1, :] > 5
# print(tensor1[mask]) # 不是全维度
# 处理原张量进行转置操作,只要实现后面两个翻转
# 如果直接转置的话，会处理成全翻转，原3 5 4 会翻转成4 5 3
tensor2 = tensor1.mT

In [19]:
# 将mask应用到tensor2上，形状匹配前两个维度
print(tensor2[mask].mT)

tensor([[3, 2, 1, 4, 3, 2, 9],
        [9, 8, 6, 9, 7, 8, 6],
        [7, 7, 6, 6, 2, 8, 2],
        [9, 3, 9, 2, 9, 6, 1],
        [7, 3, 7, 2, 3, 3, 5]])


In [21]:
# 选取符合条件的矩阵：元素（1，2）> 5
mask = tensor1[:, 1, 2] > 5
print(mask)

tensor([False, False,  True])


In [22]:
print(tensor1[mask])

tensor([[[7, 3, 2, 9],
         [4, 7, 8, 6],
         [6, 2, 8, 2],
         [2, 9, 6, 1],
         [5, 3, 3, 5]]])


In [ ]:
# 前面的维度要一致 使用布尔索引的话