In [1]:
import torch

# 张量形状操作

## 交换维度

In [2]:
# 1）transpose()交换两个维度
# 这是2 3 6 的张量
tensor1 = torch.randint(1, 10, (2, 3, 6))
print(tensor1)
# 这里交换后是 2 6 3 的张量
print(tensor1.transpose(1, 2))  # 交换第1维和第2维


tensor([[[8, 5, 7, 4, 3, 6],
         [4, 6, 1, 9, 6, 2],
         [4, 8, 1, 8, 8, 3]],

        [[8, 4, 6, 3, 6, 1],
         [4, 2, 5, 1, 1, 3],
         [5, 3, 9, 5, 5, 1]]])
tensor([[[8, 4, 4],
         [5, 6, 8],
         [7, 1, 1],
         [4, 9, 8],
         [3, 6, 8],
         [6, 2, 3]],

        [[8, 4, 5],
         [4, 2, 3],
         [6, 5, 9],
         [3, 1, 5],
         [6, 1, 5],
         [1, 3, 1]]])


In [3]:
# 这里就是 6 3 2 的张量
print(tensor1.transpose(0, 2))  # 全翻转

tensor([[[8, 8],
         [4, 4],
         [4, 5]],

        [[5, 4],
         [6, 2],
         [8, 3]],

        [[7, 6],
         [1, 5],
         [1, 9]],

        [[4, 3],
         [9, 1],
         [8, 5]],

        [[3, 6],
         [6, 1],
         [8, 5]],

        [[6, 1],
         [2, 3],
         [3, 1]]])


In [4]:
# 2.重新排列多个维度
print(tensor1.permute(0, 2, 1))

tensor([[[8, 4, 4],
         [5, 6, 8],
         [7, 1, 1],
         [4, 9, 8],
         [3, 6, 8],
         [6, 2, 3]],

        [[8, 4, 5],
         [4, 2, 3],
         [6, 5, 9],
         [3, 1, 5],
         [6, 1, 5],
         [1, 3, 1]]])


调整形状

In [5]:
tensor1 = torch.randint(1, 10, (3, 5, 4))
print(tensor1)


tensor([[[2, 2, 5, 5],
         [4, 9, 6, 2],
         [8, 1, 5, 6],
         [1, 3, 3, 1],
         [4, 3, 3, 6]],

        [[5, 3, 7, 8],
         [3, 6, 3, 8],
         [2, 7, 6, 1],
         [6, 8, 4, 1],
         [4, 6, 5, 3]],

        [[1, 6, 7, 4],
         [6, 3, 8, 9],
         [9, 4, 8, 3],
         [2, 4, 3, 1],
         [4, 7, 3, 9]]])


In [6]:
# 6 10 的张量，总大小需要一致
print(tensor1.reshape(6,10))

tensor([[2, 2, 5, 5, 4, 9, 6, 2, 8, 1],
        [5, 6, 1, 3, 3, 1, 4, 3, 3, 6],
        [5, 3, 7, 8, 3, 6, 3, 8, 2, 7],
        [6, 1, 6, 8, 4, 1, 4, 6, 5, 3],
        [1, 6, 7, 4, 6, 3, 8, 9, 9, 4],
        [8, 3, 2, 4, 3, 1, 4, 7, 3, 9]])


In [8]:
print(tensor1.reshape(3,-1))

tensor([[2, 2, 5, 5, 4, 9, 6, 2, 8, 1, 5, 6, 1, 3, 3, 1, 4, 3, 3, 6],
        [5, 3, 7, 8, 3, 6, 3, 8, 2, 7, 6, 1, 6, 8, 4, 1, 4, 6, 5, 3],
        [1, 6, 7, 4, 6, 3, 8, 9, 9, 4, 8, 3, 2, 4, 3, 1, 4, 7, 3, 9]])


In [7]:
# 直接变成行向量
print(tensor1.reshape(-1))

tensor([2, 2, 5, 5, 4, 9, 6, 2, 8, 1, 5, 6, 1, 3, 3, 1, 4, 3, 3, 6, 5, 3, 7, 8,
        3, 6, 3, 8, 2, 7, 6, 1, 6, 8, 4, 1, 4, 6, 5, 3, 1, 6, 7, 4, 6, 3, 8, 9,
        9, 4, 8, 3, 2, 4, 3, 1, 4, 7, 3, 9])


In [ ]:
# 2）view()调整张量的形状，需要内存连续。共享内存
# is_contiguous()判断是否内存连续
# contiguous()转换为内存连续

In [11]:
tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print(tensor1.is_contiguous()) # is_contiguous()判断是否内存连续

tensor([[[2, 1, 1, 4],
         [4, 4, 7, 3],
         [1, 1, 6, 5],
         [6, 7, 6, 5],
         [3, 1, 5, 5]],

        [[5, 5, 4, 4],
         [7, 6, 5, 1],
         [6, 1, 4, 8],
         [4, 7, 8, 3],
         [3, 4, 8, 5]],

        [[3, 2, 3, 8],
         [7, 4, 8, 8],
         [3, 5, 6, 8],
         [1, 7, 5, 7],
         [4, 4, 4, 4]]])
True


In [12]:
#
'''
tensor1.view(-1, 10)
#         ↑    ↑
#         |    └─ 第1维固定为10
#         └────── 第0维自动计算 = 总元素数 / 10

关键要点:
✅ -1 表示"自动推断"
✅ 只能有一个 -1
✅ 总元素数必须能整除
✅ view 要求内存连续
✅ 常用于展平、重塑张量
'''
print(tensor1.view(-1, 10))

tensor([[2, 1, 1, 4, 4, 4, 7, 3, 1, 1],
        [6, 5, 6, 7, 6, 5, 3, 1, 5, 5],
        [5, 5, 4, 4, 7, 6, 5, 1, 6, 1],
        [4, 8, 4, 7, 8, 3, 3, 4, 8, 5],
        [3, 2, 3, 8, 7, 4, 8, 8, 3, 5],
        [6, 8, 1, 7, 5, 7, 4, 4, 4, 4]])


In [14]:
tensor1 = tensor1.T
print(tensor1.is_contiguous()) # is_contiguous()判断是否内存连续
print(tensor1.contiguous().view(-1)) # contiguous()强制内存连续

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [13]:
import torch

# 创建一个有20个元素的张量
tensor1 = torch.arange(20)  # tensor([0, 1, 2, ..., 19])
print(tensor1.shape)  # torch.Size([20])

# 使用 view(-1, 10)
result = tensor1.view(-1, 10)
print(result.shape)  # torch.Size([2, 10])
#                  ↑
#              -1 被自动推断为 2

# 为什么是 2？
# 总元素数 = 20
# 已知第1维 = 10
# 所以第0维 = 20 / 10 = 2
# 在 PyTorch 的 view() 方法中，**-1 表示"自动推断"**这个维度的大小。
# 总元素数 = 所有维度的乘积
# -1 的位置 = 总元素数 / 其他维度的乘积



torch.Size([20])
torch.Size([2, 10])


In [ ]:
# 批次图像: (batch_size, channels, height, width)
images = torch.randn(32, 3, 28, 28)  # 32张RGB图像，28×28像素

# 展平为: (batch_size, channels*height*width)
flattened = images.view(32, -1)
print(flattened.shape)  # torch.Size([32, 2352])
#                       3 × 28 × 28 = 2352


In [ ]:
# 原始: (batch, seq_len, embedding)
x = torch.randn(16, 10, 128)

# 合并前两个维度: (batch*seq_len, embedding)
x_reshaped = x.view(-1, 128)
print(x_reshaped.shape)  # torch.Size([160, 128])


In [ ]:
# 展平后处理，再恢复
x = torch.randn(16, 10, 128)
flat = x.view(-1, 128)       # (160, 128)
# ... 一些操作 ...
restored = flat.view(16, 10, 128)  # 恢复原状


## 增加或删除维度

In [16]:

tensor1 = torch.tensor([1, 2, 3])
print(tensor1)
# 在0维上增加一个维度 1 * 3
print(tensor1.unsqueeze(dim=0))
# 在1维上增加一个维度 3 * 1
print(tensor1.unsqueeze(dim=1))
# 在-1维上增加一个维度
print(tensor1.unsqueeze(dim=-1))

'''
tensor([1, 2, 3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
tensor([[1],
        [2],
        [3]])
'''


tensor([1, 2, 3])
tensor([[1, 2, 3]])
tensor([[1],
        [2],
        [3]])
tensor([[1],
        [2],
        [3]])


In [17]:
tensor1 = torch.tensor([1, 2, 3, 4, 5])
print(tensor1.unsqueeze_(dim=0))
# 减少维度
print(tensor1.squeeze())


tensor([[1, 2, 3, 4, 5]])
tensor([1, 2, 3, 4, 5])


## 张量的拼接操作

In [18]:
# 1）torch.cat()张量拼接，按已有维度拼接。除拼接维度外，其他维度大小须相同
tensor1 = torch.randint(1, 9, (2, 2, 5))
tensor2 = torch.randint(1, 9, (2, 1, 5))
print(tensor1)
print(tensor2)
# 拼接后：2 * 3 * 5
print(torch.cat([tensor1, tensor2], dim=1))

'''
tensor([[[3, 1, 6, 4, 7],
         [6, 4, 8, 3, 8]],

        [[7, 4, 3, 5, 8],
         [8, 8, 2, 8, 3]]])
tensor([[[1, 1, 3, 2, 5]],

        [[2, 1, 8, 6, 2]]])
tensor([[[3, 1, 6, 4, 7],
         [6, 4, 8, 3, 8],
         [1, 1, 3, 2, 5]],

        [[7, 4, 3, 5, 8],
         [8, 8, 2, 8, 3],
         [2, 1, 8, 6, 2]]])
'''


tensor([[[3, 1, 6, 4, 7],
         [6, 4, 8, 3, 8]],

        [[7, 4, 3, 5, 8],
         [8, 8, 2, 8, 3]]])
tensor([[[1, 1, 3, 2, 5]],

        [[2, 1, 8, 6, 2]]])
tensor([[[3, 1, 6, 4, 7],
         [6, 4, 8, 3, 8],
         [1, 1, 3, 2, 5]],

        [[7, 4, 3, 5, 8],
         [8, 8, 2, 8, 3],
         [2, 1, 8, 6, 2]]])


In [21]:
# 2）torch.stack()张量堆叠，按新维度堆叠。所有张量形状必须一致
torch.manual_seed(42)
tensor1 = torch.randint(1, 9, (3, 1, 5))
tensor2 = torch.randint(1, 9, (3, 1, 5))
print(tensor1)
print(tensor2)
tensor3 = torch.stack([tensor1, tensor2], dim=2)

print(tensor3)
print(tensor3.shape) # torch.Size([3, 1, 2, 5])

'''
tensor([[[7, 4, 5, 7, 3]],

        [[8, 5, 5, 7, 2]],

        [[3, 7, 3, 3, 8]]])

tensor([[[5, 4, 8, 8, 3]],

        [[6, 5, 2, 8, 4]],

        [[6, 6, 2, 8, 4]]])

tensor([[[[7, 4, 5, 7, 3],
          [5, 4, 8, 8, 3]]],


        [[[8, 5, 5, 7, 2],
          [6, 5, 2, 8, 4]]],


        [[[3, 7, 3, 3, 8],
          [6, 6, 2, 8, 4]]]])


'''

tensor([[[7, 4, 5, 7, 3]],

        [[8, 5, 5, 7, 2]],

        [[3, 7, 3, 3, 8]]])
tensor([[[5, 4, 8, 8, 3]],

        [[6, 5, 2, 8, 4]],

        [[6, 6, 2, 8, 4]]])
tensor([[[[7, 4, 5, 7, 3],
          [5, 4, 8, 8, 3]]],


        [[[8, 5, 5, 7, 2],
          [6, 5, 2, 8, 4]]],


        [[[3, 7, 3, 3, 8],
          [6, 6, 2, 8, 4]]]])
torch.Size([3, 1, 2, 5])


'\ntensor([[[7, 4, 5, 7, 3]],\n\n        [[8, 5, 5, 7, 2]],\n\n        [[3, 7, 3, 3, 8]]])\n\ntensor([[[5, 4, 8, 8, 3]],\n\n        [[6, 5, 2, 8, 4]],\n\n        [[6, 6, 2, 8, 4]]])\n\ntensor([[[[7, 4, 5, 7, 3],\n          [5, 4, 8, 8, 3]]],\n\n\n        [[[8, 5, 5, 7, 2],\n          [6, 5, 2, 8, 4]]],\n\n\n        [[[3, 7, 3, 3, 8],\n          [6, 6, 2, 8, 4]]]])\n\n\n'