In [1]:
import  torch

In [14]:
# 定义数据
x = torch.tensor(10.0)
y = torch.tensor([[3.0]])
print(x,y)

tensor(10.) tensor([[3.]])


In [15]:
# 初始化参数
w  = torch.rand(1,1,requires_grad=True)
b = torch.rand(1,1,requires_grad=True)

In [17]:
# 前向传播，得到输出
z = w * x + b
print(z)

tensor([[10.3892]], grad_fn=<AddBackward0>)


In [18]:
print(x.is_leaf)
print(w.is_leaf)
print(b.is_leaf)
print(y.is_leaf)
print(z.is_leaf)


True
True
True
True
False


自动微分的关键就是记录节点的数据与运算。数据记录在张量的data属性中，计算记录在张量的grad_fn属性中。
计算图根据搭建方式可分为静态图和动态图，PyTorch是动态图机制，在计算的过程中逐步搭建计算图，同时对每个Tensor都存储grad_fn供自动微分使用


若设置张量参数requires_grad=True，则PyTorch会追踪所有基于该张量的操作，并在反向传播时计算其梯度。依赖于叶子节点的节点，requires_grad默认为True。当计算到根节点后，在根节点调用backward()方法即可反向传播计算计算图中所有节点的梯度。


非叶子节点的梯度在反向传播之后会被释放掉（除非设置参数retain_grad=True）。而叶子节点的梯度在反向传播之后会保留（累积）。通常需要使用optimizer.zero_grad()清零参数的梯度。


有时我们希望将某些计算移动到计算图之外，可以使用Tensor.detach()返回一个新的变量，该变量与原变量具有相同的值，但丢失计算图中如何计算原变量的信息。换句话说，梯度不会在该变量处继续向下传播。


In [19]:
# 设置损失函数
loss = torch.nn.MSELoss()
loss_value = loss(z,y)
print(loss_value)
print(loss_value.is_leaf)

tensor(54.5999, grad_fn=<MseLossBackward0>)
False


In [20]:
# 反向传播
# 这里必须是一个标量的张量，必须是一个数值
loss_value.backward()

In [21]:
# 查看梯度
print(w.grad)
print(b.grad)

'''
tensor([[147.7835]])
tensor([[14.7783]])
'''

tensor([[147.7835]])
tensor([[14.7783]])
