In [3]:
import  torch

In [5]:
# 用两组数据进行对比
x1 = torch.tensor([1.0,2.0,3.0],requires_grad=True)
x2 = torch.tensor([1.0,2.0,3.0],requires_grad=True)
print(x1)
print(x2)
'''
tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.], requires_grad=True)
'''


tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.], requires_grad=True)


In [19]:
y1 = x1.sigmoid()
y2 = x2.sigmoid()
print(y1)
print(y2)
'''
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)
'''

tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)


'\ntensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)\ntensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)\n'

In [14]:
# 使用sum函数作为loss
# y1.sum().backward()
# print(x1.grad) # tensor([0.3932, 0.2100, 0.0904])

tensor([0.5898, 0.3150, 0.1355])


In [15]:
# y2.sum().backward()
# print(x2.grad) # tensor([0.1966, 0.1050, 0.0452])

tensor([0.3932, 0.2100, 0.0904])


In [16]:
# 区别对待
# 都是用来底层用来存储数据的
z1 = y1.data # 只做读取，不做修改，修改后会影响梯度计算
z2 = y2.detach()
print(z1)
print(z2)
'''
tensor([0.7311, 0.8808, 0.9526])
tensor([0.7311, 0.8808, 0.9526])
'''

tensor([0.7311, 0.8808, 0.9526])
tensor([0.7311, 0.8808, 0.9526])


In [20]:
print(z1.requires_grad)
print(z2.requires_grad)

False
False


In [22]:
z1.zero_()
z2.zero_()
print(y1)
print(y2)

'''
tensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)
tensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)
'''

tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)
tensor([0.7311, 0.8808, 0.9526], grad_fn=<SigmoidBackward0>)


'\ntensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)\ntensor([0., 0., 0.], grad_fn=<SigmoidBackward0>)\n'

In [23]:
# y1.sum().backward()
# print(x1.grad)

# y2.sum().backward()
# print(x2.grad)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
#

#

#